import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useCreateUserWithEmailAndPassword, useSignInWithEmailAndPassword } from "react-firebase-hooks/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import { auth } from "../../firebase/firebase";

const Signin = () => {
  const [user] = useAuthState(auth);
  const router = useRouter();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLogin, setIsLogin] = useState(true);

  const [signInWithEmailAndPassword,, loadingLogin, errorLogin] = useSignInWithEmailAndPassword(auth);
  const [createUserWithEmailAndPassword,, loadingSignup, errorSignup] = useCreateUserWithEmailAndPassword(auth);

  useEffect(() => {
    if (user) router.push("/");
  }, [user, router]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isLogin) {
      await signInWithEmailAndPassword(email, password);
    } else {
      await createUserWithEmailAndPassword(email, password);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="h-screen bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 w-full py-36 px-4"
    >
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0" />
      </Head>

      <div className="flex flex-col items-center justify-center">
        <img
          className="w-96"
          src="https://upload.wikimedia.org/wikipedia/en/thumb/a9/TikTok_logo.svg/1200px-TikTok_logo.svg.png"
          alt=""
        />

        <div className="bg-white shadow lg:w-1/3 md:w-1/2 w-full p-10 mt-16 rounded-md">
          <p className="text
